apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
spec:
  selector:
    matchLabels:
      app: shopping-app
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
        - name: shopping-app
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
