# Use the official OpenJDK base image
FROM openjdk:11-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven wrapper files
COPY mvnw .
COPY .mvn .mvn

# Copy the project descriptor files
COPY pom.xml .

# Copy the source code
COPY src src

# Build the project and generate the JAR file
RUN ./mvnw package -DskipTests

# Copy the JAR file into the container at /app
COPY target/*.jar app.jar

# Expose the port that your app runs on
EXPOSE 8080

# Run the JAR file when the container launches
CMD ["java", "-jar", "app.jar"]
